# Generated by Django 4.2 on 2023-04-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_student_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
